library(ocupacoesBR)
cat("== bit64 disponivel?", requireNamespace("bit64", quietly=TRUE), "\n")
cat("== data.table?", requireNamespace("data.table", quietly=TRUE), "\n")
cat("== tibble?", requireNamespace("tibble", quietly=TRUE), "\n")
cat("== arrow?", requireNamespace("arrow", quietly=TRUE), "\n")
cat("== haven?", requireNamespace("haven", quietly=TRUE), "\n")
cat("== DIGCLASS?", requireNamespace("DIGCLASS", quietly=TRUE), "\n")

cat("\n===== B. FACTOR em n_supervisionados =====\n")
# usuario le CSV com stringsAsFactors ou usa read.csv antigo
f <- factor(c("0","5","20"))
cat("as.numeric(factor) =", as.numeric(f), " (deveria ser 0,5,20)\n")
r1 <- isco88_para_egp(rep("5220",3), conta_propria=rep(TRUE,3), n_supervisionados=f)
r2 <- isco88_para_egp(rep("5220",3), conta_propria=rep(TRUE,3), n_supervisionados=c(0,5,20))
cat("com factor :", r1, "\n")
cat("com numerico:", r2, "\n")
cat("IGUAIS?", identical(r1,r2), "\n")

cat("\n===== C. conta_propria como character 'TRUE'/'FALSE' =====\n")
print(tryCatch(isco88_para_egp("5220", conta_propria="TRUE", avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))
cat("\n===== D. conta_propria factor =====\n")
print(tryCatch(isco88_para_egp(c("5220","5220"), conta_propria=factor(c("TRUE","FALSE")), avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))
cat("\n===== E. superior numerico 0/1 vs 2 =====\n")
print(tse_para_classe(c("291","291","291"), superior=c(1,0,2)))
cat("\n===== F. superior com valores >1 / negativos =====\n")
print(tse_para_classe(c("291","291"), superior=c(-1, 0.5)))
