library(ocupacoesBR); library(bit64); library(data.table); library(tibble)
cat("===== G. integer64 (fread da RAIS) =====\n")
x64 <- as.integer64(c(111105, 225120))
cat("is.numeric:", is.numeric(x64), " is.factor:", is.factor(x64), " as.character:", as.character(x64), "\n")
print(tryCatch(cbo2002_para_isco(x64), error=function(e) paste("ERRO:", conditionMessage(e))))
t64 <- as.integer64(c(111, 169, 257))
print(tryCatch(tse_para_isco(t64), error=function(e) paste("ERRO:", conditionMessage(e))))
cat("-- integer64 com NA --\n")
n64 <- as.integer64(c(111, NA))
print(tryCatch(tse_para_isco(n64), error=function(e) paste("ERRO:", conditionMessage(e))))
cat("-- integer64 gigante (lixo de leitura) --\n")
print(tryCatch(tse_para_isco(as.integer64(9223372036854775807)), error=function(e) paste("ERRO:", conditionMessage(e))))

cat("\n===== H. coluna de data.table / tibble =====\n")
dt <- data.table(cod = c(111,169,257))
print(tryCatch(tse_para_isco(dt$cod), error=function(e) paste("ERRO:",conditionMessage(e))))
tb <- tibble(cod = c(111,169,257))
print(tryCatch(tse_para_isco(tb$cod), error=function(e) paste("ERRO:",conditionMessage(e))))
cat("-- passando o data.frame de 1 coluna inteiro (erro comum) --\n")
print(tryCatch(tse_para_isco(tb["cod"]), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(str(tse_para_isco(as.data.frame(dt))), error=function(e) paste("ERRO:",conditionMessage(e))))

cat("\n===== I. haven_labelled (SPSS/Stata, publico tipico) =====\n")
library(haven)
hl <- haven::labelled(c(111,169), c("medico"=111))
print(tryCatch(tse_para_isco(hl), error=function(e) paste("ERRO:",conditionMessage(e))))

cat("\n===== J. double com notacao cientifica / decimal =====\n")
print(tryCatch(tse_para_isco(1.11e2), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(tse_para_isco(111.0000001), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(cbo2002_para_isco(1e15), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(cbo2002_para_isco(111105.0), error=function(e) paste("ERRO:",conditionMessage(e))))
