library(ocupacoesBR)
cat("===== K. contrato de comprimento: data.frame de entrada =====\n")
df <- data.frame(cod = c(111,169,257), uf = c("RJ","SP","MG"))
r <- suppressWarnings(tse_para_isco(df))
cat("nrow(df)=",nrow(df)," length(saida)=",length(r),"  ->", r, "\n")
r2 <- suppressWarnings(tse_para_classe(df["cod"]))
cat("tse_para_classe(df['cod']) len=", length(r2), " val=", r2, "\n")
cat("-> silencioso: df$classe <- isso recicla 1 valor por TODAS as linhas\n")

cat("\n===== L. Encoding dos rotulos nos .rda =====\n")
print(table(Encoding(tse_isco$classe)))
print(table(Encoding(tse_isco$estrato)))
print(table(Encoding(isco88_medidas$rotulo)))
print(table(Encoding(cbo2002_isco88$titulo)))
cat("locale:", Sys.getlocale("LC_CTYPE"), "\n")
cat("amostra classe:", unique(tse_isco$classe)[1:4], "\n")

cat("\n===== M. duplicados e ordem =====\n")
d <- c("111","111","169","111")
cat(identical(tse_para_isco(d), c("2221","2221","1300","2221")), "\n")

cat("\n===== N. reciclagem silenciosa em checa_periodo / classe =====\n")
print(tryCatch(checa_periodo(c("211","111"), c(2000)), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(tse_para_classe(c("291","291"), superior=TRUE), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(isco88_para_egp(c("5220","5220"), conta_propria=TRUE, avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(isco88_para_egp(c("5220","5220"), n_supervisionados=5, avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))

cat("\n===== O. n_supervisionados mais longo que isco =====\n")
print(tryCatch(isco88_para_egp("5220", n_supervisionados=c(1,2,3), avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))
print(tryCatch(isco88_para_egp("5220", conta_propria=c(TRUE,FALSE,TRUE), avisar=FALSE), error=function(e) paste("ERRO:",conditionMessage(e))))
