library(ocupacoesBR)
set.seed(1)
n <- 8e6
cod <- sample(tse_isco$cod_tse, n, replace=TRUE)
cat("== 8M linhas, character ==\n")
gc(reset=TRUE)
t1 <- system.time(r1 <- tse_para_isco(cod)); print(t1)
t2 <- system.time(r2 <- tse_para_classe(cod)); print(t2)
t3 <- system.time(r3 <- tse_para_isei(cod)); print(t3)
t4 <- system.time(r4 <- suppressWarnings(tse_para_egp(cod, avisar=FALSE))); print(t4)
cat("pico de memoria (Mb):\n"); print(gc())
codn <- as.integer(cod)
cat("== 8M linhas, integer ==\n")
print(system.time(rr <- tse_para_isco(codn)))
cat("== crosswalk_tse com 8M ==\n")
print(system.time(cw <- suppressWarnings(crosswalk_tse(cod[1:1e6]))))
