suppressMessages(library(ocupacoesBR))
d <- crosswalk_tse()
cat("== linhas do dicionario:", nrow(d), "\n\n")
cat("== EGP no crosswalk_tse() (sem aviso, sem conta_propria):\n")
print(table(d$egp, useNA = "ifany"))
cat("\n== fusao TSE -> ISCO88: quantos codigos TSE por ISCO88\n")
tb <- table(table(d$isco88))
print(tb)
cat("\n== ISEI por classe (sobreposicao?)\n")
print(round(tapply(d$isei88, d$classe, function(z) c(n=sum(!is.na(z)), min=min(z,na.rm=TRUE), med=median(z,na.rm=TRUE), max=max(z,na.rm=TRUE))) |> do.call(what=rbind), 1))
